---
title: "INFO 201"
author: "Njeri Kimani"
date: "2025-06-02"
output: html_document
---

### Import libraries 
```{r}
library(tidyverse)
library(readr)
library(stringr)
library(ggplot2)
library(RColorBrewer)
```

 How do education and demographic distributions (age, race, gender) intersect with income, crime rates and access to public amenities in Seattle neighborhoods?
 1. What are the different commitmnet levels for education opprunities

#### Load in the data set & check names

```{r}
education <- read_csv("./Datasets/education_Neighborhoods_1871220638301550035.csv") %>% 
  rename(
    `Neighborhood` = `Neighborhood Name`,
    `Age 3+ in School` = `Population 3 years and over enrolled in school`,
    `Public Preschool Enrollment` = `Enrolled in nursery school or preschool public`,
    `Private Preschool Enrollment` = `Enrolled in nursery school or preschool private`,
    `Public Kindergarten Enrollment` = `Enrolled in kindergarten public`,
    `Private Kindergarten Enrollment` = `Enrolled in kindergarten private`,
    `Primary` = `Enrolled in elementary school (grades 1-8)`,
    `Secondary-Equivalent` = `Enrolled in high school (grades 9-12)`,
    `Post-Secondary` = `Enrolled in college or graduate school`
  ) %>% 
  mutate(
    `Preschool Enrollment` = `Public Preschool Enrollment` + `Private Preschool Enrollment`,
    `K Enrollment` = `Public Kindergarten Enrollment` + `Private Kindergarten Enrollment`
  ) %>% 
  select(`Neighborhood`, `Age 3+ in School`, `Preschool Enrollment`, `K Enrollment`, `Primary`, `Secondary-Equivalent`, `Post-Secondary`)

education <- education %>%
  mutate(NeighborhoodGroup = "N/A") %>%
  mutate(
    NeighborhoodGroup = if_else(str_detect(Neighborhood, "Ballard|Crown Hill|Whittier Heights|Sunset Hill/Loyal Heights|Greenwood/Phinney Ridge|Greenwood-Phinney Ridge|Broadview/Bitter Lake|Bitter Lake Village|Green Lake|Aurora-Licton Springs|Licton Springs|North Beach/Blue Ridge", ), "Ballard", NeighborhoodGroup),

    NeighborhoodGroup = if_else(str_detect(Neighborhood, "Capitol Hill|First Hill/Capitol Hill|First Hill|North Capitol Hill|Miller Park|Madison-Miller", ), "Capitol Hill", NeighborhoodGroup),

    NeighborhoodGroup = if_else(str_detect(Neighborhood, "Central Area/Squire Park|Judkins Park|Madrona/Leschi|23rd & Union-Jackson", ), "Central District", NeighborhoodGroup),

    NeighborhoodGroup = if_else(str_detect(Neighborhood, "Downtown|Downtown Commercial Core|Uptown|Belltown|Pioneer Square/International District|South Lake Union", ), "Downtown / Core", NeighborhoodGroup),

    NeighborhoodGroup = if_else(str_detect(Neighborhood, "Eastlake|Cascade/Eastlake|Montlake/Portage Bay|Madison Park", ), "Eastlake", NeighborhoodGroup),

    NeighborhoodGroup = if_else(str_detect(Neighborhood, "Queen Anne|Upper Queen Anne|Magnolia|Interbay", ), "Queen Anne / Magnolia", NeighborhoodGroup),

    NeighborhoodGroup = if_else(str_detect(Neighborhood, "Georgetown|Duwamish/SODO|Greater Duwamish", ), "SODO / Duwamish", NeighborhoodGroup),

    NeighborhoodGroup = if_else(str_detect(Neighborhood, "South Park|Rainier Beach|Columbia City|Othello|Mt. Baker/North Rainier|Mt Baker|South Beacon Hill/NewHolly|North Beacon Hill/Jefferson Park|Beacon Hill|North Beacon Hill|Seward Park", ), "South Seattle", NeighborhoodGroup),

    NeighborhoodGroup = if_else(str_detect(Neighborhood, "University District|University District|Roosevelt|Ravenna/Bryant|Wedgwood/View Ridge|Northgate/Maple Leaf|Lake City|Laurelhurst/Sand Point|Olympic Hills/Victory Heights|Cedar Park/Meadowbrook|Haller Lake", ), "University District", NeighborhoodGroup),

    NeighborhoodGroup = if_else(str_detect(Neighborhood, "West Seattle|Admiral|Alki/Admiral|Fauntleroy/Seaview|West Seattle Junction/Genesee Hill|West Seattle Junction|Morgan Junction|Arbor Heights|Highland Park|Roxhill/Westwood|Westwood-Highland Park|High Point|Riverview|North Delridge", ), "West Seattle", NeighborhoodGroup),

    NeighborhoodGroup = if_else(str_detect(Neighborhood, "Council District|Outside Villages"), "Other", NeighborhoodGroup)
  ) %>% 
  select(-Neighborhood) %>% 
  group_by(NeighborhoodGroup) %>% 
  summarize(
    `Age 3+ in School` = sum(`Age 3+ in School`),
    `Preschool Enrollment` = sum(`Preschool Enrollment`),
    `K Enrollment` = sum(`K Enrollment`),
    Primary = sum(Primary),
    `Secondary-Equivalent` = sum(`Secondary-Equivalent`),
    `Post-Secondary` = sum(`Post-Secondary`),
    Total = sum(`Age 3+ in School`, `Preschool Enrollment`,`K Enrollment`, Primary, `Secondary-Equivalent`, `Post-Secondary`)
  ) %>% 
  filter(NeighborhoodGroup != "N/A")

```

---

```{r}
race_ethnicity <- read_csv("./Datasets/race_ethnicity_Neighborhoods_-7085838689260358328.csv")
```


```{r}
race_ethnicity <- race_ethnicity %>%
  select(`Neighborhood` = `Neighborhood Name`, 
         `Total` = `Total Population`, 
         `Black` = `Black or African American Alone`,
         `Asian` = `Asian Alone` , 
         `White` = `White Alone`, 
         `Hawaiian` = `Native Hawaiian and Other Pacific Islander Alone`, 
         `Hispanic` = `Hispanic or Latino (of any race)`, 
         `AIANA` = `American Indian and Alaska Native Alone`, 
         `POC` = `Percent Persons of Color`) %>% 
  mutate(NeighborhoodGroup = "N/A") %>% 
  mutate(
  NeighborhoodGroup = if_else(str_detect(Neighborhood, "Ballard|Sunset Hill|Whittier Heights|Blue Ridge|Crown Hill|Bitter Lake|Broadview|Greenwood"), "Ballard", NeighborhoodGroup),
  NeighborhoodGroup = if_else(str_detect(Neighborhood, "Capitol Hill|First Hill/Capitol Hill|North Capitol Hill|Miller Park|Madison-Miller|First Hill"), "Capitol Hill", NeighborhoodGroup),
  NeighborhoodGroup = if_else(str_detect(Neighborhood, "Central Area|Judkins Park|Madrona|Leschi|23rd & Union-Jackson"), "Central District", NeighborhoodGroup),
  NeighborhoodGroup = if_else(str_detect(Neighborhood, "Downtown|Belltown|Pioneer Square|Uptown|South Lake Union"), "Downtown / Core", NeighborhoodGroup),
  NeighborhoodGroup = if_else(str_detect(Neighborhood, "Eastlake|Montlake|Portage Bay|Madison Park"), "Eastlake", NeighborhoodGroup),
  NeighborhoodGroup = if_else(str_detect(Neighborhood, "Queen Anne|Upper Queen Anne|Magnolia|Interbay"), "Queen Anne / Magnolia", NeighborhoodGroup),
  NeighborhoodGroup = if_else(str_detect(Neighborhood, "SODO|Duwamish|Georgetown|Greater Duwamish"), "SODO / Duwamish", NeighborhoodGroup),
  NeighborhoodGroup = if_else(str_detect(Neighborhood, "South Park|Othello|Rainier Beach|Columbia City|Mt\\. Baker|NewHolly|Beacon Hill|Seward Park|North Beacon Hill"), "South Seattle", NeighborhoodGroup),
  NeighborhoodGroup = if_else(str_detect(Neighborhood, "University District|Roosevelt|Ravenna|Bryant|Wedgwood|View Ridge|Northgate|Maple Leaf|Laurelhurst|Sand Point|Lake City"), "University District", NeighborhoodGroup),
  NeighborhoodGroup = if_else(str_detect(Neighborhood, "West Seattle|Admiral|Fauntleroy|Genesee Hill|Junction|Arbor Heights|Highland Park|Westwood|High Point|Riverview|Delridge|Morgan Junction"), "West Seattle", NeighborhoodGroup),
  NeighborhoodGroup = if_else(str_detect(Neighborhood, "Council District|Outside Villages"), "Other", NeighborhoodGroup)
) %>% 
  select(-Neighborhood) %>% 
  group_by(NeighborhoodGroup) %>% 
  summarise(
    Total = sum(Total, na.rm = TRUE),
    Black = sum(Black, na.rm = TRUE),
    Asian = sum(Asian, na.rm = TRUE),
    White = sum(White, na.rm = TRUE),
    Hawaiian = sum(Hawaiian, na.rm = TRUE),
    Hispanic = sum(Hispanic, na.rm = TRUE), 
    AIANA = sum(AIANA, na.rm = TRUE),
    POC = sum(POC, na.rm = TRUE),
    .groups = "drop"
  ) %>% 
  filter(NeighborhoodGroup != "N/A")

race_ethnicity
```


```{r}

race_ethnicity$Total[race_ethnicity$Neighborhood == "Council District 1"] 

race_ethnicity$Black[race_ethnicity$Neighborhood == "Council District 1"] 
race_ethnicity$White[race_ethnicity$Neighborhood == "Council District 1"] 

race_ethnicity <- race_ethnicity %>%
  group_by(NeighborhoodGroup) %>%
  mutate(Black = Black/Total * 100) %>%
  mutate(Asian = Asian/Total * 100) %>%
  mutate(White = White/Total * 100) %>%
  mutate(Hawaiian = Hawaiian/Total * 100) %>%
  mutate(Hispanic = Hispanic/Total * 100) %>%
  mutate(`AI/ANA` = `AIANA`/Total * 100) %>%
  mutate(POC = sum(Black, Asian, Hawaiian, Hispanic, `AIANA`))
race_ethnicity

```


```{r}
population <- read_csv("./Datasets/hh_population_types_Neighborhoods_7932363052017489999.csv")
```


```{r}
population <- population %>% 
  select(`Neighborhood Name`, `Total Population`) %>% 
  mutate(NeighborhoodGroup = ifelse(str_detect(`Neighborhood Name`,
    "Belltown|Downtown Commercial Core|Pioneer Square/International District|Uptown|Downtown|South Lake Union"), "Downtown / Core", NA)) %>%
  mutate(NeighborhoodGroup = ifelse(str_detect(`Neighborhood Name`,
    "Capitol Hill|North Capitol Hill|First Hill|First Hill/Capitol Hill"),
    "Capitol Hill", NeighborhoodGroup)) %>%
  mutate(NeighborhoodGroup = ifelse(str_detect(`Neighborhood Name`,
    "Rainier Beach|Columbia City|Seward Park|Mt. Baker/North Rainier|Othello|South Park|Riverview|Roxhill/Westwood|Highland Park"),
    "South Seattle", NeighborhoodGroup)) %>%
  mutate(NeighborhoodGroup = ifelse(str_detect(`Neighborhood Name`,
    "Duwamish/SODO|Georgetown|Greater Duwamish"), "SODO / Duwamish", NeighborhoodGroup)) %>%
  mutate(NeighborhoodGroup = ifelse(str_detect(`Neighborhood Name`,
    "Central Area/Squire Park|Judkins Park|Madrona/Leschi|23rd & Union-Jackson|Madison-Miller"), "Central District", NeighborhoodGroup)) %>%
  mutate(NeighborhoodGroup = ifelse(str_detect(`Neighborhood Name`,
    "Ballard|Sunset Hill/Loyal Heights|Whittier Heights|Crown Hill|Greenwood/Phinney Ridge|Greenwood-Phinney Ridge"),
    "Ballard", NeighborhoodGroup)) %>%
  mutate(NeighborhoodGroup = ifelse(str_detect(`Neighborhood Name`,
    "Queen Anne|Upper Queen Anne|Interbay|Magnolia"), "Queen Anne / Magnolia", NeighborhoodGroup)) %>%
  mutate(NeighborhoodGroup = ifelse(str_detect(`Neighborhood Name`,
    "West Seattle Junction|Morgan Junction|Alki/Admiral|Fauntleroy/Seaview|Arbor Heights|Genesee Hill|North Delridge"), "West Seattle", NeighborhoodGroup)) %>%
  mutate(NeighborhoodGroup = ifelse(str_detect(`Neighborhood Name`,
    "University District|Roosevelt|Ravenna/Bryant|Laurelhurst/Sand Point|Wedgwood/View Ridge"), "University District", NeighborhoodGroup)) %>%
  mutate(NeighborhoodGroup = ifelse(str_detect(`Neighborhood Name`,
    "Northgate|Olympic Hills/Victory Heights|Haller Lake|Cedar Park/Meadowbrook|Aurora-Licton Springs"), "North Seattle", NeighborhoodGroup)) %>%
  mutate(NeighborhoodGroup = ifelse(str_detect(`Neighborhood Name`,
    "Green Lake|Wallingford|Fremont"), "Green Lake / Wallingford", NeighborhoodGroup)) %>%
  mutate(NeighborhoodGroup = ifelse(str_detect(`Neighborhood Name`,
    "Eastlake|Cascade/Eastlake"), "Eastlake", NeighborhoodGroup)) %>%
  filter(!is.na(NeighborhoodGroup)) %>% 
  select(-`Neighborhood Name`) %>% 
  group_by(NeighborhoodGroup) %>% 
  summarize(
    Total = sum(`Total Population`)
  )

population
```

```{r}

education_long <- education %>%
  select(NeighborhoodGroup, `Preschool Enrollment`, `K Enrollment`, Primary, `Secondary-Equivalent`, `Post-Secondary`) %>%
  pivot_longer(
    cols = -NeighborhoodGroup,
    names_to = "School_Level",
    values_to = "Enrollment"
  )

ggplot(education_long, aes(x = School_Level, y = Enrollment, fill = School_Level)) +
  geom_bar(stat = "identity", position = "dodge") +
  facet_wrap(~ NeighborhoodGroup, scales = "free_y") +
  labs(
    title = "School Enrollment by Level Across Neighborhood Groups",
    x = "School Level",
    y = "Enrollment Count"
  ) + 
  theme(
  axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size = 5),
  strip.text = element_text(size = 5),
  plot.margin = margin(10, 10, 10, 10)
)

race_ethnicity_long <- race_ethnicity %>%
  pivot_longer(cols = c(Black, Asian, White, Hawaiian, Hispanic, AIANA), 
               names_to = "Race", values_to = "Population") 

ggplot(race_ethnicity_long, aes(x = Race, y = Population, fill = Race)) +
  geom_col(show.legend = FALSE) +   # stacked bars by default; can add position = "dodge" for side-by-side bars
  facet_wrap(~ NeighborhoodGroup, scales = "free_y") +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    strip.text = element_text(size = 9)
  ) +
  labs(
    title = "Population by Race per Neighborhood Group",
    x = "Race",
    y = "Population"
  )



```




